# Generated by Django 4.1 on 2022-08-15 05:32

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='body',
        ),
        migrations.AddField(
            model_name='post',
            name='resource_name',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='resourse_url',
            field=models.URLField(default=datetime.datetime(2022, 8, 15, 5, 32, 0, 919743, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
