# Generated by Django 4.1 on 2022-08-15 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_text_post_body_post_resource_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='resourse_url',
            new_name='resource_url',
        ),
    ]
